// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonWebApplication.Context;

namespace PokemonWebApplication.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20220105005854_Modify property IdDoPokemon")]
    partial class ModifypropertyIdDoPokemon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("PokemonWebApplication.Models.MestrePokemon", b =>
                {
                    b.Property<int>("IdDoPokemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDoPokemon");

                    b.ToTable("MestrePokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
